// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class CampaignController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _dynamicFields = "_dynamicFields";
                public readonly string _MultipleChoice = "_MultipleChoice";
                public readonly string _Question = "_Question";
                public readonly string AgentManagement = "AgentManagement";
                public readonly string BulkAddAgent = "BulkAddAgent";
                public readonly string BulkSms = "BulkSms";
                public readonly string CampaignBaseUpload = "CampaignBaseUpload";
                public readonly string CampaignView = "CampaignView";
                public readonly string CreateCampaign = "CreateCampaign";
                public readonly string CreateCampaignNew = "CreateCampaignNew";
                public readonly string NewCreateCampaign = "NewCreateCampaign";
            }
            public readonly string _dynamicFields = "~/Views/Campaign/_dynamicFields.cshtml";
            public readonly string _MultipleChoice = "~/Views/Campaign/_MultipleChoice.cshtml";
            public readonly string _Question = "~/Views/Campaign/_Question.cshtml";
            public readonly string AgentManagement = "~/Views/Campaign/AgentManagement.cshtml";
            public readonly string BulkAddAgent = "~/Views/Campaign/BulkAddAgent.cshtml";
            public readonly string BulkSms = "~/Views/Campaign/BulkSms.cshtml";
            public readonly string CampaignBaseUpload = "~/Views/Campaign/CampaignBaseUpload.cshtml";
            public readonly string CampaignView = "~/Views/Campaign/CampaignView.cshtml";
            public readonly string CreateCampaign = "~/Views/Campaign/CreateCampaign.cshtml";
            public readonly string CreateCampaignNew = "~/Views/Campaign/CreateCampaignNew.cshtml";
            public readonly string NewCreateCampaign = "~/Views/Campaign/NewCreateCampaign.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
