// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Templateprj.Controllers
{
    public partial class IncidentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public IncidentController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected IncidentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Incidents()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Incidents);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IncidentView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IncidentView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Qrc()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Qrc);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QrcView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QrcView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FlipkartAlerts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FlipkartAlerts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SystemAlerts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SystemAlerts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Customer()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Customer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RdnGetDetails()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RdnGetDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ProjectTracker()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProjectTracker);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ProjectTrackerView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProjectTrackerView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RdnAutofill()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RdnAutofill);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IncHistory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IncHistory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadHistory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadHistory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Owner()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Owner);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public IncidentController Actions { get { return MVC.Incident; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Incident";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Incident";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Incidents = "Incidents";
            public readonly string IncidentView = "IncidentView";
            public readonly string Qrc = "Qrc";
            public readonly string QrcView = "QrcView";
            public readonly string FlipkartAlerts = "FlipkartAlerts";
            public readonly string SystemAlerts = "SystemAlerts";
            public readonly string Customer = "Customer";
            public readonly string RdnGetDetails = "RdnGetDetails";
            public readonly string ProjectTracker = "ProjectTracker";
            public readonly string ProjectTrackerView = "ProjectTrackerView";
            public readonly string RdnAutofill = "RdnAutofill";
            public readonly string IncHistory = "IncHistory";
            public readonly string DownloadHistory = "DownloadHistory";
            public readonly string Owner = "Owner";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Incidents = "Incidents";
            public const string IncidentView = "IncidentView";
            public const string Qrc = "Qrc";
            public const string QrcView = "QrcView";
            public const string FlipkartAlerts = "FlipkartAlerts";
            public const string SystemAlerts = "SystemAlerts";
            public const string Customer = "Customer";
            public const string RdnGetDetails = "RdnGetDetails";
            public const string ProjectTracker = "ProjectTracker";
            public const string ProjectTrackerView = "ProjectTrackerView";
            public const string RdnAutofill = "RdnAutofill";
            public const string IncHistory = "IncHistory";
            public const string DownloadHistory = "DownloadHistory";
            public const string Owner = "Owner";
        }


        static readonly ActionParamsClass_Incidents s_params_Incidents = new ActionParamsClass_Incidents();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Incidents IncidentsParams { get { return s_params_Incidents; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Incidents
        {
            public readonly string id = "id";
            public readonly string incident = "incident";
            public readonly string fileUpload = "fileUpload";
        }
        static readonly ActionParamsClass_IncidentView s_params_IncidentView = new ActionParamsClass_IncidentView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IncidentView IncidentViewParams { get { return s_params_IncidentView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IncidentView
        {
            public readonly string model = "model";
            public readonly string search = "search";
            public readonly string export = "export";
            public readonly string open = "open";
            public readonly string monthlyreport = "monthlyreport";
            public readonly string Weektreand = "Weektreand";
            public readonly string monthtreand = "monthtreand";
        }
        static readonly ActionParamsClass_Qrc s_params_Qrc = new ActionParamsClass_Qrc();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Qrc QrcParams { get { return s_params_Qrc; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Qrc
        {
            public readonly string id = "id";
            public readonly string qrc = "qrc";
        }
        static readonly ActionParamsClass_QrcView s_params_QrcView = new ActionParamsClass_QrcView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QrcView QrcViewParams { get { return s_params_QrcView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QrcView
        {
            public readonly string model = "model";
            public readonly string search = "search";
            public readonly string export = "export";
            public readonly string open = "open";
        }
        static readonly ActionParamsClass_FlipkartAlerts s_params_FlipkartAlerts = new ActionParamsClass_FlipkartAlerts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FlipkartAlerts FlipkartAlertsParams { get { return s_params_FlipkartAlerts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FlipkartAlerts
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SystemAlerts s_params_SystemAlerts = new ActionParamsClass_SystemAlerts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SystemAlerts SystemAlertsParams { get { return s_params_SystemAlerts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SystemAlerts
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Customer s_params_Customer = new ActionParamsClass_Customer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Customer CustomerParams { get { return s_params_Customer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Customer
        {
            public readonly string status = "status";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_RdnGetDetails s_params_RdnGetDetails = new ActionParamsClass_RdnGetDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RdnGetDetails RdnGetDetailsParams { get { return s_params_RdnGetDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RdnGetDetails
        {
            public readonly string RdnNum = "RdnNum";
        }
        static readonly ActionParamsClass_ProjectTracker s_params_ProjectTracker = new ActionParamsClass_ProjectTracker();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProjectTracker ProjectTrackerParams { get { return s_params_ProjectTracker; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProjectTracker
        {
            public readonly string id = "id";
            public readonly string RdnNum = "RdnNum";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ProjectTrackerView s_params_ProjectTrackerView = new ActionParamsClass_ProjectTrackerView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProjectTrackerView ProjectTrackerViewParams { get { return s_params_ProjectTrackerView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProjectTrackerView
        {
            public readonly string model = "model";
            public readonly string search = "search";
            public readonly string export = "export";
            public readonly string open = "open";
        }
        static readonly ActionParamsClass_RdnAutofill s_params_RdnAutofill = new ActionParamsClass_RdnAutofill();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RdnAutofill RdnAutofillParams { get { return s_params_RdnAutofill; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RdnAutofill
        {
            public readonly string Rdn = "Rdn";
            public readonly string tfn = "tfn";
        }
        static readonly ActionParamsClass_IncHistory s_params_IncHistory = new ActionParamsClass_IncHistory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IncHistory IncHistoryParams { get { return s_params_IncHistory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IncHistory
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DownloadHistory s_params_DownloadHistory = new ActionParamsClass_DownloadHistory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadHistory DownloadHistoryParams { get { return s_params_DownloadHistory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadHistory
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Owner s_params_Owner = new ActionParamsClass_Owner();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Owner OwnerParams { get { return s_params_Owner; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Owner
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _IncHistory = "_IncHistory";
                public readonly string Customer = "Customer";
                public readonly string FlipkartAlerts = "FlipkartAlerts";
                public readonly string Incidents = "Incidents";
                public readonly string IncidentView = "IncidentView";
                public readonly string ProjectTracker = "ProjectTracker";
                public readonly string ProjectTrackerView = "ProjectTrackerView";
                public readonly string Qrc = "Qrc";
                public readonly string QrcView = "QrcView";
                public readonly string SystemAlerts = "SystemAlerts";
            }
            public readonly string _IncHistory = "~/Views/Incident/_IncHistory.cshtml";
            public readonly string Customer = "~/Views/Incident/Customer.cshtml";
            public readonly string FlipkartAlerts = "~/Views/Incident/FlipkartAlerts.cshtml";
            public readonly string Incidents = "~/Views/Incident/Incidents.cshtml";
            public readonly string IncidentView = "~/Views/Incident/IncidentView.cshtml";
            public readonly string ProjectTracker = "~/Views/Incident/ProjectTracker.cshtml";
            public readonly string ProjectTrackerView = "~/Views/Incident/ProjectTrackerView.cshtml";
            public readonly string Qrc = "~/Views/Incident/Qrc.cshtml";
            public readonly string QrcView = "~/Views/Incident/QrcView.cshtml";
            public readonly string SystemAlerts = "~/Views/Incident/SystemAlerts.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_IncidentController : Templateprj.Controllers.IncidentController
    {
        public T4MVC_IncidentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IncidentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Incidents(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Incidents);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            IncidentsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void IncidentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.IncidentModel incident, System.Web.HttpPostedFileBase fileUpload);

        [NonAction]
        public override System.Web.Mvc.ActionResult Incidents(Templateprj.Models.IncidentModel incident, System.Web.HttpPostedFileBase fileUpload)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Incidents);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "incident", incident);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileUpload", fileUpload);
            IncidentsOverride(callInfo, incident, fileUpload);
            return callInfo;
        }

        [NonAction]
        partial void IncidentViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.ViewModel model, string search, string export, string open, string monthlyreport, string Weektreand, string monthtreand);

        [NonAction]
        public override System.Web.Mvc.ActionResult IncidentView(Templateprj.Models.ViewModel model, string search, string export, string open, string monthlyreport, string Weektreand, string monthtreand)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IncidentView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "export", export);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "open", open);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "monthlyreport", monthlyreport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Weektreand", Weektreand);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "monthtreand", monthtreand);
            IncidentViewOverride(callInfo, model, search, export, open, monthlyreport, Weektreand, monthtreand);
            return callInfo;
        }

        [NonAction]
        partial void QrcOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Qrc(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Qrc);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            QrcOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void QrcOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.QrcModel qrc);

        [NonAction]
        public override System.Web.Mvc.ActionResult Qrc(Templateprj.Models.QrcModel qrc)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Qrc);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "qrc", qrc);
            QrcOverride(callInfo, qrc);
            return callInfo;
        }

        [NonAction]
        partial void QrcViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.ViewModel model, string search, string export, string open);

        [NonAction]
        public override System.Web.Mvc.ActionResult QrcView(Templateprj.Models.ViewModel model, string search, string export, string open)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QrcView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "export", export);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "open", open);
            QrcViewOverride(callInfo, model, search, export, open);
            return callInfo;
        }

        [NonAction]
        partial void FlipkartAlertsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult FlipkartAlerts(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FlipkartAlerts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            FlipkartAlertsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SystemAlertsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult SystemAlerts(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SystemAlerts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            SystemAlertsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CustomerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string status);

        [NonAction]
        public override System.Web.Mvc.ActionResult Customer(string status)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Customer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "status", status);
            CustomerOverride(callInfo, status);
            return callInfo;
        }

        [NonAction]
        partial void CustomerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.CusModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Customer(Templateprj.Models.CusModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Customer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CustomerOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void RdnGetDetailsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string RdnNum);

        [NonAction]
        public override System.Web.Mvc.JsonResult RdnGetDetails(string RdnNum)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RdnGetDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RdnNum", RdnNum);
            RdnGetDetailsOverride(callInfo, RdnNum);
            return callInfo;
        }

        [NonAction]
        partial void ProjectTrackerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string RdnNum);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProjectTracker(string id, string RdnNum)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProjectTracker);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "RdnNum", RdnNum);
            ProjectTrackerOverride(callInfo, id, RdnNum);
            return callInfo;
        }

        [NonAction]
        partial void ProjectTrackerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.ProjectTracker model);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProjectTracker(Templateprj.Models.ProjectTracker model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProjectTracker);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ProjectTrackerOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ProjectTrackerViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.ProjectViewModel model, string search, string export, string open);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProjectTrackerView(Templateprj.Models.ProjectViewModel model, string search, string export, string open)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProjectTrackerView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "search", search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "export", export);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "open", open);
            ProjectTrackerViewOverride(callInfo, model, search, export, open);
            return callInfo;
        }

        [NonAction]
        partial void RdnAutofillOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string Rdn, string tfn);

        [NonAction]
        public override System.Web.Mvc.JsonResult RdnAutofill(string Rdn, string tfn)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RdnAutofill);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Rdn", Rdn);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tfn", tfn);
            RdnAutofillOverride(callInfo, Rdn, tfn);
            return callInfo;
        }

        [NonAction]
        partial void IncHistoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult IncHistory(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IncHistory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            IncHistoryOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DownloadHistoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadHistory(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadHistory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DownloadHistoryOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void OwnerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.CusModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Owner(Templateprj.Models.CusModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Owner);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            OwnerOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
