// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Templateprj.Controllers
{
    public partial class InstantSmsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected InstantSmsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SendInstatntSms()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendInstatntSms);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetSmsCount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetSmsCount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Instantsmsreport()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Instantsmsreport);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public InstantSmsController Actions { get { return MVC.InstantSms; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "InstantSms";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "InstantSms";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string InstantSms = "InstantSms";
            public readonly string SendInstatntSms = "SendInstatntSms";
            public readonly string GetSmsCount = "GetSmsCount";
            public readonly string Instantsmsreport = "Instantsmsreport";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string InstantSms = "InstantSms";
            public const string SendInstatntSms = "SendInstatntSms";
            public const string GetSmsCount = "GetSmsCount";
            public const string Instantsmsreport = "Instantsmsreport";
        }


        static readonly ActionParamsClass_SendInstatntSms s_params_SendInstatntSms = new ActionParamsClass_SendInstatntSms();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendInstatntSms SendInstatntSmsParams { get { return s_params_SendInstatntSms; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendInstatntSms
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetSmsCount s_params_GetSmsCount = new ActionParamsClass_GetSmsCount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetSmsCount GetSmsCountParams { get { return s_params_GetSmsCount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetSmsCount
        {
            public readonly string query = "query";
        }
        static readonly ActionParamsClass_Instantsmsreport s_params_Instantsmsreport = new ActionParamsClass_Instantsmsreport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Instantsmsreport InstantsmsreportParams { get { return s_params_Instantsmsreport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Instantsmsreport
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string InstantSms = "InstantSms";
                public readonly string InstantSmsReciver = "InstantSmsReciver";
            }
            public readonly string Index = "~/Views/InstantSms/Index.cshtml";
            public readonly string InstantSms = "~/Views/InstantSms/InstantSms.cshtml";
            public readonly string InstantSmsReciver = "~/Views/InstantSms/InstantSmsReciver.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_InstantSmsController : Templateprj.Controllers.InstantSmsController
    {
        public T4MVC_InstantSmsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void InstantSmsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult InstantSms()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InstantSms);
            InstantSmsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SendInstatntSmsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.InstantSms.InstantSmsCommand model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendInstatntSms(Templateprj.Models.InstantSms.InstantSmsCommand model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendInstatntSms);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SendInstatntSmsOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetSmsCountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.InstantSms.GetSmsCountQuery query);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetSmsCount(Templateprj.Models.InstantSms.GetSmsCountQuery query)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetSmsCount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "query", query);
            GetSmsCountOverride(callInfo, query);
            return callInfo;
        }

        [NonAction]
        partial void InstantsmsreportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.InstantSms.InstantSmsModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Instantsmsreport(Templateprj.Models.InstantSms.InstantSmsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Instantsmsreport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            InstantsmsreportOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
