// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Templateprj.Controllers
{
    public partial class ReportsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReportsController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ReportsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult viewcustomerfeedbackdetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.viewcustomerfeedbackdetails);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ReportsController Actions { get { return MVC.Reports; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Reports";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Reports";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string FeedbackReports = "FeedbackReports";
            public readonly string viewcustomerfeedbackdetails = "viewcustomerfeedbackdetails";
            public readonly string DetailedReport = "DetailedReport";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string FeedbackReports = "FeedbackReports";
            public const string viewcustomerfeedbackdetails = "viewcustomerfeedbackdetails";
            public const string DetailedReport = "DetailedReport";
        }


        static readonly ActionParamsClass_FeedbackReports s_params_FeedbackReports = new ActionParamsClass_FeedbackReports();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FeedbackReports FeedbackReportsParams { get { return s_params_FeedbackReports; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FeedbackReports
        {
            public readonly string model = "model";
            public readonly string Download = "Download";
        }
        static readonly ActionParamsClass_viewcustomerfeedbackdetails s_params_viewcustomerfeedbackdetails = new ActionParamsClass_viewcustomerfeedbackdetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_viewcustomerfeedbackdetails viewcustomerfeedbackdetailsParams { get { return s_params_viewcustomerfeedbackdetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_viewcustomerfeedbackdetails
        {
            public readonly string customerId = "customerId";
        }
        static readonly ActionParamsClass_DetailedReport s_params_DetailedReport = new ActionParamsClass_DetailedReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DetailedReport DetailedReportParams { get { return s_params_DetailedReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DetailedReport
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string DetailedReport = "DetailedReport";
                public readonly string FeedbackReports = "FeedbackReports";
            }
            public readonly string DetailedReport = "~/Views/Reports/DetailedReport.cshtml";
            public readonly string FeedbackReports = "~/Views/Reports/FeedbackReports.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ReportsController : Templateprj.Controllers.ReportsController
    {
        public T4MVC_ReportsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void FeedbackReportsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FeedbackReports()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FeedbackReports);
            FeedbackReportsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FeedbackReportsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.feedbackreportmodel model, string Download);

        [NonAction]
        public override System.Web.Mvc.ActionResult FeedbackReports(Templateprj.Models.feedbackreportmodel model, string Download)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FeedbackReports);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Download", Download);
            FeedbackReportsOverride(callInfo, model, Download);
            return callInfo;
        }

        [NonAction]
        partial void viewcustomerfeedbackdetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string customerId);

        [NonAction]
        public override System.Web.Mvc.ActionResult viewcustomerfeedbackdetails(string customerId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.viewcustomerfeedbackdetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerId", customerId);
            viewcustomerfeedbackdetailsOverride(callInfo, customerId);
            return callInfo;
        }

        [NonAction]
        partial void DetailedReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetailedReport()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailedReport);
            DetailedReportOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailedReportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Templateprj.Models.DeatailedReportModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult DetailedReport(Templateprj.Models.DeatailedReportModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DetailedReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            DetailedReportOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
